import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Title from '../components/ui/Title';

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Next Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title title="home"/>
      </main>

      
    </div>
  )
}
